version: 2.1

orbs:
  ggshield: gitguardian/ggshield@volatile
  browser-tools: circleci/browser-tools@1.4.4
  sonarcloud: sonarsource/sonarcloud@2.0.0
  doppler: conpago/doppler@1.3.5

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      TRIGGER_SOURCE: <<pipeline.trigger_source>>
      CIRCLE_RANGE: <<pipeline.git.base_revision>>...<<pipeline.git.revision>>
      TRIGGER_TYPE: <<pipeline.trigger_parameters.circleci.trigger_type>>
      EVENT_TYPE: <<pipeline.trigger_parameters.circleci.event_type>>
      GITHUB_APP_CHECKOUT_SHA: <<pipeline.trigger_parameters.github_app.checkout_sha>>
      GITHUB_APP_REF: <<pipeline.trigger_parameters.github_app.ref>>
      GITHUB_APP_COMMIT_SHA: <<pipeline.trigger_parameters.github_app.commit_sha>>
      GITHUB_APP_BRANCH: <<pipeline.trigger_parameters.github_app.branch>>
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "env"


workflows:
  build_test_deploy:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
      - code_test:
          requires:
            - build
          context: SonarCloud
      - browser_test:
          requires:
            - build
  say-hello-workflow:
    jobs:
      - say-hello
